### ISSUE TITLE
Spam received with url.epoch.tw link attached

### ISSUE THREAD

**Issue by winstonsung** [memochou1993/shortener-ui#1]
Hello,

I'm a co-administrator of a Line OpenChat.

In 00:07 (UTC) / 08:07 (UTC+8) today (2024-05-06), we received the following message in the Line OpenChat I moderated:

> ```
> 🎁💡💡新週愉快 🔕
>   📈  本 週 衝-🌹 擊  22000！! 
> 賺—錢 良 幾到！！ 
> 今 日 📣📣  開 - 市  💐前  即 公  佈  2-3檔  標  的！  
> 
>    ♥️♥️ 赢       3️⃣ 0️⃣ %    
> 
> 🎏 節 後 首 秀！🎏
> 有需要可以 點👇  
> ⬇️ ⬇️ ⬇️
> url.epoch.tw/JknmL
> 
> 🌺🌺gc
> ```

![Screenshot of the spam message](https://github.com/memochou1993/shortener-ui/assets/52590365/3cc3d560-0d53-4965-bc73-c7a0c7417d85)

It is very clear that it's a spam message, and it included the link `https://url.epoch.tw/JknmL` .

I'm afraid that the URL shortener service/website might be abused for spamming.

Please take a look into this issue for spam prevention.

Thanks.

Sincerely,
Sung C. C. (Winston Sung)

**Comment by memochou1993** [comment]
@winstonsung 

Hi,

感謝回報，目前沒有辦法預先檢查網頁內容是否為垃圾訊息。

你可以先把該使用者從群組中剔除。

如果有想到不錯的 idea，歡迎一起討論，謝謝。

BTW, 我也是淡江的 :)

**Comment by winstonsung** [comment]
應該可以先這樣？
* 將非正常連結下架
* 建立網址（plain/regex）封鎖名單

**Comment by memochou1993** [comment]
對於已經產生的連結，我覺得特別做封鎖機制的效益可能不大，而且這個服務沒有很多人用

目前可以做的是限定 HTTPS 網址，可以杜絕掉一些不正經的網站

**Comment by memochou1993** [comment]
最近在整理，把一些服務關掉了。

暫時先不繼續維護～
